### ISSUE TITLE
useParentRequest attribute apparently breaks backend module

### ISSUE THREAD

**Issue by DrNik** [sitegeist/Sitegeist.Monocle#57] opened 2017-11-09 15:04 UTC
The backend module seems to be broken with this error:

```
Could not resolve a route and its corresponding URI for the given parameters.

This may be due to referring to a not existing package / controller / action while building a link or URI. Refer to log and check the backtrace for more details.

Exception Code	1301610453
Exception Type	Neos\FluidAdaptor\Core\ViewHelper\Exception
Thrown in File	Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_FluidAdaptor_ViewHelpers_Uri_ActionViewHelper.php
Line	91
Original File	Packages/Framework/Neos.FluidAdaptor/Classes/ViewHelpers/Uri/ActionViewHelper.php

Nested Exception
Could not resolve a route and its corresponding URI for the given parameters.

This may be due to referring to a not existing package / controller / action while building a link or URI. Refer to log and check the backtrace for more details.

Exception Code	1301610453
Exception Type	Neos\Flow\Mvc\Exception\NoMatchingRouteException
Log Reference	20171109155431ef1916
Thrown in File	Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_Mvc_Routing_Router.php
Line	189
Original File	Packages/Framework/Neos.Flow/Classes/Mvc/Routing/Router.php
```
**Affected version**: 3.0.1

**Step to reproduce**:
+ install the package via composer
+ access backend module from Neos backend interface

**Possible Cause/Fix** : the error seems due to the attribute `useParentRequest: 1` in `Sitegeist.Monocle/Resources/Private/Templates/Styleguide/Index.html`.
Removing it seems to solve the issue and the module is accessible again.

**Comment by mficzel** [comment] 2017-11-16 18:47
@DrNik thank you for the feedback, but i cannot reproduce your problem. For me the useParentRequest os actually necessary to work.

Can you check this with monocle 4.0, there the routes are integrated automatically and might behave differently. (Attention breaking changes)

**Comment by DrNik** [comment] 2017-11-17 07:57
@mficzel I'll definetly give it a try as I was actually testing your packages to check how could we introduce it in our workflow.

I'll let you know how my tests will end up.

Thanks

**Comment by grebaldi** [comment] 2018-01-16 16:20
@DrNik Can we close this? Or are you still experiencing issues?

**Comment by DrNik** [comment] 2018-01-17 10:06
Hi @grebaldi sorry for my late answer.
I just made a quick test with the suggested version and I can confirm the problem seems gone, but I'm facing an authentication problem. Do you prefer me to open a new issue in case?

Thanks,
Nicola

**Comment by grebaldi** [comment] 2018-01-21 16:45
@DrNik Yep, that would be great, thanks :)

**Comment by DrNik** [comment] 2018-01-22 08:02
Ok @grebaldi then this one can be closed.

**Closed** 2018-01-24 07:30 UTC
