### ISSUE TITLE
Preview doesn't resize based on image content

### ISSUE THREAD

**Issue by wanicode** [sitegeist/Sitegeist.Monocle#14] opened 2016-09-02 13:00 UTC
When i want to display an img-Tag with a src, Monocle sometimes doesn't resize the preview window based on the picture size.

**Comment by mficzel** [comment] 2016-12-09 16:22
Yes a known problem ... it is not so easy to get the load event of an iframe

**Comment by grebaldi** [comment] 2016-12-23 10:22
This might solve it: #33

**Comment by mficzel** [comment] 2017-11-16 22:17
I close this since i cannot reproduce this with actual monocle ui any more

**Closed by mficzel** 2017-11-16 22:17 UTC
