### ISSUE TITLE
Previews not rendering

### ISSUE THREAD

**Issue by hphoeksma** [sitegeist/Sitegeist.Monocle#46] opened 2017-08-08 21:24 UTC
Hi,

looking forward to use this package!

I can't get it to work though...

**Setup**
- Neos (3.1.4)
- Sitegeist.Monocle (v2.0.7)

**Steps taken**
- Added routes (above neos routes)
- Added policies 
- Added the Settings and adjusted styles & js references
- Added a @styleguide annotation as in the readme to one of my prototypes
- Force cleared caches

**Result**
`
Exception Code | 0
-- | --
Error
Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Sitegeist_Monocle_Controller_ApiController.php
77
Packages/Plugins/Sitegeist.Monocle/Classes/Sitegeist/Monocle/Controller/ApiController.php
`

Maybe I am missing something?

**Comment by grebaldi** [comment] 2017-09-14 07:23
Hey, 

sorry for the late response :(

Since you opened this issue, we had a new Major release. You should give it a try to confirm, whether your issue's still there.

As for the problem in v2.0.7: The error message points to a line in which the ApiController is trying to figure out your active site package, but it is not clear what goes wrong there. There's a couple of things you could check though:

* Do your prototypes reside in your active site package?
* Is the `type` field in your site package's `composer.json` set to `neos-site`?

At what point does that error message appear? is it during some CLI operation (which would be weird), or do you actually see it in the browser window when calling the styleguide? Or is it the result of an XHR call?

Best regards,
Wilhelm

**Comment by mficzel** [comment] 2017-11-16 18:50
I close this because there is not reproducible without more details. If the problem occurs again on a fresh monocle version please open a new issue or contact us via neos-slack#project-styleguide.

**Closed by mficzel** 2017-11-16 18:50 UTC
